{% set name = "xorg-xauth" %}
{% set version = "1.1.5" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://www.x.org/releases/individual/app/{{ name.split('-')[1] }}-{{ version }}.tar.xz
  sha256: a4000e2f441facebf569026bedecc23ba262cc6927be52070abe0002625cfbe0

build:
  # xorg-libxdmcp, libxcb, libx11, libice aren't available on Windows because their dependencies clash with m2/msys2 and mingw64/ucrt64 toolchains.
  skip: true  # [win]
  number: 0

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - pkg-config
    - gnuconfig
    - make
    - autoconf
    - automake
    - gettext
    - libtool
  host:
    - pthread-stubs ==0.3
    - xorg-libx11 {{ xorg_libx11 }}
    - xorg-libxau {{ xorg_libxau }}
    - xorg-libxext {{ xorg_libxext }}
    - xorg-libxmu {{ xorg_libxmu }}
    - xorg-xtrans ==1.6.0
    - xorg-xorgproto {{ xorg_xorgproto }}
    - xorg-util-macros ==1.20.2

test:
  commands:
    - 'xauth -h 2>&1 | grep -q "usage:  xauth \[-options ...\] \[command arg ...\]"'          # [unix]

about:
  home: https://www.x.org/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: X.Org authorization settings program
  description: |
    The X.org xauth program
  dev_url: https://gitlab.freedesktop.org/xorg/app/xauth
  doc_url: https://gitlab.freedesktop.org/xorg/app/xauth

extra:
  recipe-maintainers:
    - ehfd
